/**
 * 自动生成的 homepage 更新脚本
 * 生成时间: 2026-09-13T05:39:21.578Z
 * 需要更新的条目数: 185
 */

export const HOMEPAGE_UPDATES: Record<string, string> = {
  'dsh-free-search': 'https://github.com/DDDMUC/dsh-free-search#readme', // npm registry homepage
  'dsh-builtin-browser': 'https://github.com/wqty123/dsh-browser', // npm registry homepage
  'dsh-agent-browser': 'https://github.com/shantanugoel/dsh-browser-control#readme', // npm registry homepage
  'dsh-dream-skin': 'https://github.com/RevolutionLA/dsh-dream-skin#readme', // npm registry homepage
  'dsh-plugin-wallpaper-engine': 'https://github.com/elysia395/dsh-wallpaper-engine#readme', // npm registry homepage
  'dsh-pet': 'https://github.com/PC2005-cloud/dsh-pet#readme', // npm registry homepage
  'dsh-dafeiyu': 'https://github.com/QCYTSN/dsh-dafeiyu#readme', // npm registry homepage
  'whale-on-desk': 'https://cookiesheep.github.io/whale-on-desk', // npm registry homepage
  'dsh-whale-widget': 'https://github.com/MeteorNOX/DeepSeek-Balance-Whale-Widget#readme', // npm registry homepage
  '@aiwayds/dsh-tui-pi': 'https://github.com/fan56/dsh-tui-pi#readme', // npm registry homepage
  'dsh-vscode-mode': 'https://github.com/Lenonss/DSH_VsCodeMode', // npm registry homepage
  '@kobenfang/dsh-eyes': 'https://www.npmjs.com/package/%40kobenfang%2Fdsh-eyes', // npm package page fallback
  'dsh-image-gen': 'https://github.com/shanliuling/dsh-image-gen#readme', // npm registry homepage
  '@flowingspring/dsh-voco': 'https://github.com/lgquan/dsh-voco#readme', // npm registry homepage
  'dsh-agent-voice': 'https://github.com/meliodascz89/dsh-agent-voice#readme', // npm registry homepage
  'dsh-pocket': 'https://github.com/shaobeichen/dsh-pocket', // npm registry homepage
  'dsh-mobile': 'https://github.com/saya-ch/dsh-mobile#readme', // npm registry homepage
  'dsh-remote': 'https://github.com/flymysql/dsh-remote', // npm registry homepage
  'ds-harness-remote': 'https://github.com/liguobao/ds-harness-remote#readme', // npm registry homepage
  'dsh-remote-plugin': 'https://github.com/Blank-not-black/dsh-Remote', // npm registry homepage
  'pi2dsh': 'https://github.com/weijiafu14/pi2dsh#readme', // npm registry homepage
  'dsh-univer-office': 'https://github.com/dream-num/dsh-univer-office', // npm registry homepage
  'dsh-feishu-bot': 'https://github.com/PlutoKeating/dsh-lark-bot#readme', // npm registry homepage
  'dsh-lark-bot': 'https://github.com/PlutoKeating/dsh-lark-bot#readme', // npm registry homepage
  'dsh-office-tools': 'https://github.com/kw78/dsh-office-tools#readme', // npm registry homepage
  'dsh-excel-chat': 'https://github.com/hccccc01333/dsh-excel-chat', // npm registry homepage
  'dsh-office': 'https://github.com/Fayelin12/dsh-office#readme', // npm registry homepage
  'dsh-wecom': 'https://github.com/TtTRz/dsh-wecom#readme', // npm registry homepage
  'dsh-wechat': 'https://github.com/pan17/dsh-wechat#readme', // npm registry homepage
  '@huanlin/dsh-plugin-better-sidebar-plugin-office': 'https://www.npmjs.com/package/%40huanlin%2Fdsh-plugin-better-sidebar-plugin-office', // npm package page fallback
  'dsh-fund-research': 'https://github.com/PerryLink/dsh-fund-research#readme', // npm registry homepage
  'dsh-xueqiu': 'https://github.com/wanderer-yk/dsh-xueqiu#readme', // npm registry homepage
  'dsh-cost-meter': 'https://github.com/Han-1413141/dsh-cost-meter#readme', // npm registry homepage
  'dsh-quant': 'https://www.npmjs.com/package/dsh-quant', // npm package page fallback
  'clawock-dsh': 'https://kcnyu.github.io/clawock/', // npm registry homepage
  'dsh-win32': 'https://github.com/sjh9714/dsh-win32#readme', // npm registry homepage
  'dsh-plugin-ops': 'https://github.com/f-infinite-z/dsh-plugin-ops#readme', // npm registry homepage
  'dsh-memory-eternal': 'https://github.com/EternalNight996/dsh-memory-eternal', // npm registry homepage
  'dsh-session-manager': 'https://github.com/hkkz9522/dsh-session-manager', // npm registry homepage
  '@morlay/session-rdb': 'https://github.com/morlay/session-rdb.git', // npm registry repository
  '@morlay/session-branch': 'https://github.com/morlay/better-session.git', // npm registry repository
  '@morlay/ui-conversation-message-actions': 'https://github.com/morlay/better-session.git', // npm registry repository
  'meow-memory': 'https://github.com/Phant0Meow/dsh-meow-memory#readme', // npm registry homepage
  'dsh-plugin-model-proxy': 'https://www.npmjs.com/package/dsh-plugin-model-proxy', // npm package page fallback
  'dsh-llm-fallbacks': 'https://github.com/omdsh-dev/dsh-llm-fallbacks#readme', // npm registry homepage
  'dsh-agy-link': 'https://github.com/amlyczz/dsh-agy-link#readme', // npm registry homepage
  'dsh-coding-subscription-oauth': 'https://github.com/lninghaha/dsh-coding-subscription-oauth#readme', // npm registry homepage
  'dsh-codex-subscription': 'https://github.com/WSL043/dsh-codex-subscription', // npm registry homepage
  'dsh-codex-connect': 'https://github.com/franksong2702/dsh-codex-connect#readme', // npm registry homepage
  '@eddyskywalker/dsh-chatgpt-subscription': 'https://github.com/Aa728848/dsh-chatgpt-subscription#readme', // npm registry homepage
  'dsh-routing-suite': 'https://github.com/dragonbaba/dsh-routing-suite#readme', // npm registry homepage
  'dsh-plugin': 'https://dsh-plugin.org', // npm registry homepage
  'dshmarket': 'https://dshmarket.com', // npm registry homepage
  'dsh-find-plugin': 'https://github.com/awesome-dsh-plugin/dsh-find-plugin#readme', // npm registry homepage
  'dsh-plugin-catalog': 'https://awesome-dsh-plugin.com', // npm registry homepage
  'dshhub-market': 'https://www.dshhub.co', // npm registry homepage
  'upstream-radar': 'https://github.com/MicroMilo/upstream-radar#readme', // npm registry homepage
  'dsh-plugin-updates': 'https://awesome-dsh-plugin.com', // npm registry homepage
  'dsh-webui-auth': 'https://www.npmjs.com/package/dsh-webui-auth', // npm package page fallback
  'dsh-config-manager': 'https://github.com/xiajiajun516/dsh-config-manager#readme', // npm registry homepage
  'dsh-harmony': 'https://github.com/memorax-ai/dsh-harmony#readme', // npm registry homepage
  'dsh-qingagent': 'https://github.com/void2anything/dsh-qingagent#readme', // npm registry homepage
  'lunheng-article-pipeline': 'https://github.com/zuoyunlai/lunheng-article-pipeline-dsh#readme', // npm registry homepage
  'gongwen-skill': 'https://github.com/linhut/gongwen-skill#readme', // npm registry homepage
  '@sunjuntao/dsh-prompt-library': 'https://github.com/master1Sun/dsh-prompt-library#readme', // npm registry homepage
  'dsh-vibe-math': 'https://github.com/ChongCyrus/Vibe-Mathematics#readme', // npm registry homepage
  '@waterwx/dsh-novel-forge': 'https://github.com/watersxya/dsh-novel-forge', // npm registry homepage
  'dsh-mcp-connector': 'https://github.com/duhu2000/dsh-mcp-connector#readme', // npm registry homepage
  'dsh-mcp-panel': 'https://github.com/PerryLink/dsh-mcp-panel#readme', // npm registry homepage
  '@microi.net/cli': 'https://microi.net/doc/v8-engine/vs-code-plugin.html', // npm registry homepage
  'huaweicloud-devkit': 'https://github.com/huaweicloud/huaweicloud-devkit#readme', // npm registry homepage
  '@tt-a1i/archify-dsh': 'https://github.com/tt-a1i/archify/tree/main/integrations/deepseek-harness', // npm registry homepage
  'dsh-chat-import': 'https://github.com/Nwflower/dsh-chat-import', // npm registry homepage
  'dsh-movein': 'https://github.com/sjh9714/dsh-movein#readme', // npm registry homepage
  'dsh-client-auto-continue': 'https://github.com/HsiangNianian/dsh-auto-continue', // npm registry homepage
  'dsh-plugin-ima-sync': 'https://github.com/nan1010082085/dsh-plugin-ima-sync#readme', // npm registry homepage
  'dsh-session-log-repair': 'https://github.com/jsoncode/dsh-session-log-repair#readme', // npm registry homepage
  'deepseek-harness-zh_pro': 'https://github.com/magian1127/deepseek-harness-zh_pro#readme', // npm registry homepage
  '@huanlin/dsh-plugin-better-locale': 'https://www.npmjs.com/package/%40huanlin%2Fdsh-plugin-better-locale', // npm package page fallback
  '@lk251066/dsh-tui': 'https://github.com/lk251066/dsh-tui-pro#readme', // npm registry homepage
  'beauticode-dsh': 'https://github.com/starsstreaming/beautiCode#readme', // npm registry homepage
  'dsh-pdf-edit': 'https://github.com/Whatsmore-nf/dsh-pdf-edit#readme', // npm registry homepage
  'dsh-tauri': 'https://github.com/dsh-tauri-desk/dsh-tauri-plugins#readme', // npm registry homepage
  'dsh-plugin-subscriptions': 'https://github.com/V1ki/dsh-plugin-subscriptions#readme', // npm registry homepage
  'dsh-tiddlywiki': 'https://github.com/bbqisbbq/dsh-tiddlywiki#readme', // npm registry homepage
  'dsh-any-background': 'https://github.com/Tkingxiao/dsh-any-background#readme', // npm registry homepage
  'aqua-deepseek': 'https://github.com/xiaoyu7044/aqua-deepseek#readme', // npm registry homepage
  'dsh-permission-rules': 'https://github.com/PerryLink/dsh-permission-rules#readme', // npm registry homepage
  'dsh-codex-sync': 'https://github.com/Walvez/dsh-codex-sync', // npm registry homepage
  'dsh-smooth-stream': 'https://laplace-bit.github.io/dsh-smooth-stream/', // npm registry homepage
  'dsh-ssh-tui': 'https://github.com/cyjyyd/dsh-ssh-tui#readme', // npm registry homepage
  'dsh-auth-gate': 'https://github.com/TecFancy/dsh-auth-gate', // npm registry homepage
  'dsh-browser': 'https://github.com/ben7am1n/dsh-browser#readme', // npm registry homepage
  'dsh-prompt-history': 'https://github.com/Xiaofei-fei/dsh-prompt-history#readme', // npm registry homepage
  'dsh-notify-me': 'https://github.com/chromoany/dsh-notify-me#readme', // npm registry homepage
  'iterate-plugin': 'https://github.com/jingzhao-l/iterate-skill/tree/main/harness/iterate-plugin', // npm registry homepage
  'dsh-tauri-panel': 'https://github.com/dsh-tauri-desk/dsh-tauri-plugins#readme', // npm registry homepage
  'dsh-deepread': 'https://github.com/xiehuan123/dsh-deepread#readme', // npm registry homepage
  'dsh-usage-stats': 'https://github.com/lanlandeli/dsh-usage-stats#readme', // npm registry homepage
  'dsh-mimir': 'https://github.com/1692775560/dsh-Mimir-Academic-research', // npm registry repository
  'dsh-workbench': 'https://github.com/lee259/dsh-workbench#readme', // npm registry homepage
  'dsh-mcp-sync': 'https://github.com/nan1010082085/dsh-mcp-sync#readme', // npm registry homepage
  'dsh-plugin-capabilities': 'https://github.com/qinyre/dsh-plugin-capabilities#readme', // npm registry homepage
  '@kubor/dsh-bloom-theme': 'https://github.com/webkubor/dsh-bloom-theme#readme', // npm registry homepage
  'dsh-settings-nav-organizer': 'https://github.com/zhengjy01/dsh-settings-nav-organizer#readme', // npm registry homepage
  'dsh-local-ai': 'https://github.com/PerryLink/dsh-local-ai#readme', // npm registry homepage
  'dsh-vision-proxy': 'https://github.com/Flyvhidbwo/dsh-vision-proxy#readme', // npm registry homepage
  'dsh-tauri-ui': 'https://github.com/dsh-tauri-desk/dsh-tauri-plugins#readme', // npm registry homepage
  'dsh-status-rotator': 'https://github.com/01Virex/dsh-status-rotator#readme', // npm registry homepage
  'dsh-tray-launcher': 'https://github.com/fancr-code/dsh-tray-launcher#readme', // npm registry homepage
  'dsh-tool-vision': 'https://github.com/Scorp1o117/dsh-tool-vision', // npm registry homepage
  'dsh-testkit': 'https://github.com/iiwish/dsh-testkit#readme', // npm registry homepage
  '@mstar-harness/dsh': 'https://github.com/btspoony/mstar-harness#readme', // npm registry homepage
  'dsh-concurrency-guard': 'https://github.com/fu827707013/dsh-concurrency-guard', // npm registry homepage
  'dsh-memento': 'https://github.com/PerryLink/dsh-memento#readme', // npm registry homepage
  'dsh-checkpoint-rewind': 'https://github.com/PerryLink/dsh-checkpoint-rewind#readme', // npm registry homepage
  'dsh-tauri-worktree': 'https://github.com/dsh-tauri-desk/dsh-tauri-plugins#readme', // npm registry homepage
  '@eternalnight/dsh-theme': 'https://github.com/EternalNight996/dsh-theme', // npm registry homepage
  'dsh-full-remote': 'https://github.com/JUANWANG-BUAA/dsh-full-remote#readme', // npm registry homepage
  'dsh-deepseek-balance-widget': 'https://github.com/crazy-L118/dsh-deepseek-balance-widget#readme', // npm registry homepage
  '@awiki/dsh-plugin': 'https://github.com/AgentConnect/dsh-awiki#readme', // npm registry homepage
  'dsh-knowledge': 'https://github.com/Soren-ABT/dsh-knowledge', // npm registry homepage
  '@isomoes/dsh-ikanban': 'https://github.com/isomoes/ikanban#readme', // npm registry homepage
  'dsh-dingo': 'https://github.com/february2015/dsh-dingo', // npm registry homepage
  'dsh-auto-review': 'https://github.com/PerryLink/dsh-auto-review#readme', // npm registry homepage
  '@crazy_th/dsh-computer-use': 'https://github.com/ThreeBody6666/dsh-computer-use#readme', // npm registry homepage
  '@huiliyi37/dsh-office': 'https://www.npmjs.com/package/%40huiliyi37%2Fdsh-office', // npm package page fallback
  'dsh-harbor-evolution': 'https://github.com/istarwyh/harbor-self-evolving#readme', // npm registry homepage
  '@p-dsh-market/conversation-knowledge-map': 'https://www.npmjs.com/package/%40p-dsh-market%2Fconversation-knowledge-map', // npm package page fallback
  'dsh-plugin-install': 'https://github.com/qinyre/dsh-plugin-install#readme', // npm registry homepage
  'dsh-session-pin': 'https://github.com/PerryLink/dsh-session-pin#readme', // npm registry homepage
  '@aiwayds/dsh-dcp': 'https://github.com/fan56/dsh-dcp', // npm registry homepage
  '@dsh-enhanced/acp': 'https://github.com/22-ai-00/dsh-enhanced', // npm registry repository
  'dsh-plugin-lookatstudy': 'https://github.com/Kaiji-Z/dsh-plugin-lookatstudy#readme', // npm registry homepage
  'dsh-desktop-windows': 'https://github.com/ReachGa0/dsh-desktop#readme', // npm registry homepage
  'dsh-plugin-vajraclaw': 'https://dr-os.io', // npm registry homepage
  'dsh-gitbash-shell': 'https://github.com/KannaKuron/dsh-gitbash-shell', // npm registry homepage
  'dsh-bloub-mood': 'https://github.com/Yuuhann1999/dsh-bloub-mood#readme', // npm registry homepage
  'relay-dsh-plugin-codex': 'https://github.com/yangbobo2021/relay-dsh-plugin-codex#readme', // npm registry homepage
  'dsh-lsp-actions': 'https://github.com/PerryLink/dsh-lsp-actions#readme', // npm registry homepage
  'dsh-image-pathify': 'https://github.com/dami9527/dsh-image-pathify#readme', // npm registry homepage
  'dsh-codex-timeline': 'https://github.com/Wine-Red/dsh-codex-timeline#readme', // npm registry homepage
  'dsh-ai4scholar': 'https://ai4scholar.net?src=dsh', // npm registry homepage
  'dsh-quota-panel': 'https://github.com/wenzetan/dsh-quota-panel#readme', // npm registry homepage
  '@agi-fans/dsh-tui': 'https://omdsh.agi.fans/', // npm registry homepage
  'dsh-crew': 'https://github.com/stuarthu/dsh-crew#readme', // npm registry homepage
  'dsh-archived-chats': 'https://github.com/Ultronen/dsh-archived-chats', // npm registry homepage
  'dsh-peak-indicator': 'https://github.com/future007s/dsh-peak-indicator#readme', // npm registry homepage
  'dsh-plugin-marketplace': 'https://github.com/Scorp1o117/dsh-plugin-marketplace', // npm registry homepage
  'dsh-plugin-wiki-tools': 'https://github.com/Lion-1209/dsh-plugin-wiki-tools#readme', // npm registry homepage
  'dsh-xray': 'https://github.com/alloevil/dsh-xray#readme', // npm registry homepage
  'dsh-project-orchestrator': 'https://github.com/zhangz-2018/dsh-project-orchestrator#readme', // npm registry homepage
  'dsh-map-tools': 'https://github.com/HorusJiang/dsh-map-tools#readme', // npm registry homepage
  'picturereader': 'https://github.com/jing-hy/picturereader#readme', // npm registry homepage
  'wallpaper-engine-dsh': 'https://github.com/Weilv-D/wallpaper-engine-dsh#readme', // npm registry homepage
  '@kiwifruit/dsh-jit-viewer': 'https://www.npmjs.com/package/%40kiwifruit%2Fdsh-jit-viewer', // npm package page fallback
  'dsh-output-styles': 'https://github.com/PerryLink/dsh-output-styles#readme', // npm registry homepage
  'dsh-advisor': 'https://github.com/omdsh-dev/dsh-advisor#readme', // npm registry homepage
  'dsh-composer-history': 'https://github.com/PerryLink/dsh-composer-history#readme', // npm registry homepage
  '@moguiyu/dsh-tool-tavily-search': 'https://github.com/moguiyu/dsh-tavily#readme', // npm registry homepage
  'dsh-observe': 'https://github.com/PerryLink/dsh-observe#readme', // npm registry homepage
  'dsh-mpkg-wallpaper': 'https://github.com/XHR666/dsh-mpkg-wallpaper', // npm registry homepage
  'dsh-auto-classifier': 'https://github.com/PAKIKNOWLEDGE/dsh-auto-classifier#readme', // npm registry homepage
  'dsh-updater-npm': 'https://github.com/SiriusWJ/dsh-updater-npm#readme', // npm registry homepage
  'dsh-email': 'https://github.com/STARDUSTLC666/dsh-email#readme', // npm registry homepage
  'dsh-acp-server': 'https://github.com/dushaobindoudou/dsh-acp#readme', // npm registry homepage
  'dsh-chat-sync': 'https://github.com/nan1010082085/dsh-chat-sync#readme', // npm registry homepage
  'dsh-voice-mode': 'https://github.com/qishuilalala/dsh-voice-mode#readme', // npm registry homepage
  'dsh-tool-normalizer': 'https://github.com/merenguesL/dsh-tool-normalizer#readme', // npm registry homepage
  'dsh-plugin-vetting': 'https://github.com/truelove-dreamer/dsh-plugin-vetting#readme', // npm registry homepage
  'dsh-auth': 'https://github.com/hxy91819/dsh-auth#readme', // npm registry homepage
  'dsh-daoing-memory': 'https://github.com/daoing/dsh-daoing-memory', // npm registry homepage
  'oh-my-knowledge': 'https://oh-my-knowledge.pages.dev', // npm registry homepage
  'dsh-quota': 'https://github.com/Minokun/dsh-quota#readme', // npm registry homepage
  'dsh-diagram': 'https://github.com/hanzhangzzz/dsh-diagram#readme', // npm registry homepage
  'dsh-kb-rag': 'https://github.com/Breeze136/dsh-kb-rag#readme', // npm registry homepage
  '@dshline/dshline': 'https://dshline.xyz', // npm registry homepage
  'dsh-meme': 'https://yyh-001.github.io/dsh-meme/', // npm registry homepage
  'dsh-plugin-balance': 'https://github.com/Andrew111888/dsh-plugin-balance', // npm registry homepage
  'dsh-ai-team': 'https://github.com/yunqiangwu/dsh-ai-team#readme', // npm registry homepage
  'dsh-f': 'https://github.com/PlutoKeating/dsh-lark-bot#readme', // npm registry homepage
  'dsh-plugin-usage-meter': 'https://github.com/fancr-code/dsh-plugin-usage-meter#readme', // npm registry homepage
  'dsh-research-report': 'https://github.com/PerryLink/dsh-research-report#readme', // npm registry homepage
  'dsh-retrace': 'https://github.com/yamingmou/dsh-retrace#readme', // npm registry homepage
  'dsh-vision-router': 'https://github.com/ysr666/dsh-vision-router', // npm registry homepage
};
